// 领域事件名称目录。事件只追加、不可原地改写；更正通过后继事件表达。
export const EventType = Object.freeze({
  // 建档
  BRAND_REGISTERED: "BRAND_REGISTERED",
  OPERATOR_REGISTERED: "OPERATOR_REGISTERED",
  STORE_REGISTERED: "STORE_REGISTERED",
  CATEGORY_REGISTERED: "CATEGORY_REGISTERED",
  STANDARD_PUBLISHED: "STANDARD_PUBLISHED",
  STANDARD_DEPRECATED: "STANDARD_DEPRECATED",

  // 授权链
  LICENSE_GRANTED: "LICENSE_GRANTED",
  LICENSE_APPROVAL_DECIDED: "LICENSE_APPROVAL_DECIDED",
  LICENSE_CLOSED_BY_CHANGE: "LICENSE_CLOSED_BY_CHANGE", // 主体变更：旧许可关闭但责任留存
  LICENSE_SCOPE_SUSPENDED: "LICENSE_SCOPE_SUSPENDED", // 局部停售 / 暂停许可生效
  LICENSE_SCOPE_RESUMED: "LICENSE_SCOPE_RESUMED", // 复查通过后按范围恢复
  LICENSE_REVOKED: "LICENSE_REVOKED",
  UNAUTHORIZED_OPERATION_DETECTED: "UNAUTHORIZED_OPERATION_DETECTED", // 发现无授权实际经营者/越权转授

  // 巡检案件
  CASE_OPENED: "CASE_OPENED",
  ISSUE_RECORDED: "ISSUE_RECORDED", // 绑定检查当时的标准版本与证据
  RISK_SUGGESTED: "RISK_SUGGESTED", // 自动分级，仅供参考
  RISK_CONFIRMED: "RISK_CONFIRMED", // 检查员确认
  ENFORCEMENT_DECIDED: "ENFORCEMENT_DECIDED",
  APPEAL_FILED: "APPEAL_FILED",
  APPEAL_DECIDED: "APPEAL_DECIDED",
  REMEDIATION_SUBMITTED: "REMEDIATION_SUBMITTED",
  REMEDIATION_REVIEWED: "REMEDIATION_REVIEWED", // 另一角色复核
  REMEDIATION_REVIEW_CONFLICTED: "REMEDIATION_REVIEW_CONFLICTED", // 并发复核冲突标记
  REINSPECTION_RECORDED: "REINSPECTION_RECORDED",
  REINSTATEMENT_DECIDED: "REINSTATEMENT_DECIDED",
  ESCALATION_RAISED: "ESCALATION_RAISED",
  CASE_CLOSED: "CASE_CLOSED",

  // 离线回执
  RECEIPT_REGISTERED: "RECEIPT_REGISTERED",
  RECEIPT_MERGED: "RECEIPT_MERGED", // 同内容指纹归并
  RECEIPT_CONTENT_INVESTIGATION_OPENED: "RECEIPT_CONTENT_INVESTIGATION_OPENED", // 同回执号异内容
  RECEIPT_INVESTIGATION_RESOLVED: "RECEIPT_INVESTIGATION_RESOLVED",

  // 通知 outbox（幂等补发）
  NOTIFICATION_SCHEDULED: "NOTIFICATION_SCHEDULED",
  NOTIFICATION_HELD: "NOTIFICATION_HELD",
  NOTIFICATION_RESCHEDULED: "NOTIFICATION_RESCHEDULED",
  NOTIFICATION_CANCELLED: "NOTIFICATION_CANCELLED",
  NOTIFICATION_DISPATCHED: "NOTIFICATION_DISPATCHED",
});
